<?php

declare(strict_types=1);

namespace Miniblog\Engine\Command;

use DanBettles\Marigold\CssMinifier;
use DanBettles\Marigold\TemplateEngine\Engine;
use DOMDocument;
use DOMElement;
use Miniblog\Engine\ErrorsService;
use RuntimeException;

use function file_put_contents;

use const false;
use const LIBXML_NOBLANKS;
use const null;
use const PHP_EOL;

/**
 * Compiles the error pages for the project.  This command should be run every time the config is changed.
 */
class CompileProjectErrorPagesCommand extends AbstractCommand
{
    /**
     * @var string
     */
    public const COMMAND_NAME = 'compile-project-error-pages';

    /**
     * @throws RuntimeException If it failed to create a file.
     */
    public function __invoke(): int
    {
        /** @var ErrorsService */
        $errorsService = $this->get('errorsService');
        // @todo Remove comment?
        $comment = "<!-- N.B. File generated by `{$this->getScriptName()}` -->";
        /** @var Engine */
        $templateEngine = $this->get('templateEngine');

        foreach ($errorsService->getPagePathnames() as $statusCode => $errorPagePathname) {
            $renderPathname = $errorsService->createRenderPathname($statusCode);
            $html = $comment . PHP_EOL . $templateEngine->render($renderPathname);
            $html = $this->minifyWebPage($html);
            $fpcResult = file_put_contents($errorPagePathname, $html);

            if (false === $fpcResult) {
                throw new RuntimeException("Failed to create file `{$errorPagePathname}`.");
            }

            $this->getConsole()->writeLn("Created {$errorPagePathname}");
        }

        return self::SUCCESS;
    }

    private function minifyWebPage(string $html): string
    {
        $domDocument = new DOMDocument('1.0', 'utf8');
        $domDocument->formatOutput = false;
        $domDocument->loadHTML($html, LIBXML_NOBLANKS);

        $cssMinifier = new CssMinifier();

        /** @var DOMElement $styleElem */
        foreach ($domDocument->getElementsByTagName('style') as $styleElem) {
            if (null === $styleElem->nodeValue) {
                continue;
            }

            $styleElem->nodeValue = $cssMinifier->minify($styleElem->nodeValue);
        }

        $html = $domDocument->saveHTML();

        if (false === $html) {
            throw new RuntimeException('Failed to save the minified web page.');
        }

        return $html;
    }
}
